channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
      - robocorp-browser==0.4.1
      - robocorp-excel==0.4.0
      - robocorp-http==0.2.0
      - robocorp-tasks==0.2.1
