[tool.robo]
name = "RPA Challenge"
description = "A simple example robot that solves the RPA Challenge"
python = "3.9.13"

[tool.robo.dependencies]
robocorp-tasks="0.2.1"
robocorp-browser="0.4.0"
robocorp-excel="0.4.0"
robocorp-http="0.2.0"

[tool.robo.dev-dependencies]
ruff="0.0.260"
black="23.3.0"

[tool.robocorp.log]
log_filter_rules = [
    {name = "playwright", kind = "log_on_project_call"},
    {name = "robocorp.browser", kind = "log_on_project_call"},
    {name = "robocorp.excel", kind = "log_on_project_call"},
    {name = "robocorp.http", kind = "log_on_project_call"},
]
